// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace projetoTopicos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Abrigo", b =>
                {
                    b.Property<int>("abrigoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnderecoID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("qtdPets")
                        .HasColumnType("INTEGER");

                    b.HasKey("abrigoID");

                    b.HasIndex("EnderecoID")
                        .IsUnique();

                    b.ToTable("Abrigos");
                });

            modelBuilder.Entity("Adocao", b =>
                {
                    b.Property<int>("AdocaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbrigoID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpfTutor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("petID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("realizadaEm")
                        .HasColumnType("TEXT");

                    b.HasKey("AdocaoID");

                    b.HasIndex("AbrigoID");

                    b.HasIndex("petID")
                        .IsUnique();

                    b.ToTable("Adocoes");
                });

            modelBuilder.Entity("Endereco", b =>
                {
                    b.Property<int>("EnderecoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataCricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("logradouro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EnderecoID");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Pet", b =>
                {
                    b.Property<int>("petID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbrigoID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("porte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("petID");

                    b.HasIndex("AbrigoID");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Abrigo", b =>
                {
                    b.HasOne("Endereco", "Endereco")
                        .WithOne("Abrigo")
                        .HasForeignKey("Abrigo", "EnderecoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Adocao", b =>
                {
                    b.HasOne("Abrigo", "Abrigo")
                        .WithMany("Adocoes")
                        .HasForeignKey("AbrigoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pet", "Pet")
                        .WithOne("Adocao")
                        .HasForeignKey("Adocao", "petID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abrigo");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Pet", b =>
                {
                    b.HasOne("Abrigo", "Abrigo")
                        .WithMany("Pets")
                        .HasForeignKey("AbrigoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abrigo");
                });

            modelBuilder.Entity("Abrigo", b =>
                {
                    b.Navigation("Adocoes");

                    b.Navigation("Pets");
                });

            modelBuilder.Entity("Endereco", b =>
                {
                    b.Navigation("Abrigo")
                        .IsRequired();
                });

            modelBuilder.Entity("Pet", b =>
                {
                    b.Navigation("Adocao")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
